### PR TITLE
(WIP) Typescript declaration

### LINKED ISSUE #10: Add typings
Would be cool for this library to have typings in a `d.ts` file so it would have a better editor support

### PR DESCRIPTION
**Pull request by me-shaon**
This PR will fix #10

### CODE REVIEW

**Comment by motiejunas** [comment]
What is the status?

**Comment by fredsossa1** [comment]
I've taken a look and if we want to have the correct types, we may have to remove the prehook with the automatic generation because it will keep bringing back any.
Unless you're okay with that.

**Comment by me-shaon** [comment]
@fredsossa1 Good point. I agree. Do you want to contribute to this one?

**Comment by jeremybarbet** [comment]
@me-shaon @fredsossa1 I started this some time ago https://github.com/mailersend/mailersend-nodejs/pull/33 but didn't have time to finish it, but feel free to jump on it and continue it.

**Pull request closed without merging**
